language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - ruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
branches:
  only:
    - master
install: true
before_script:
  - gem install --no-rdoc --no-ri rake
  - gem install --no-rdoc --no-ri rdoc
  - gem install --no-rdoc --no-ri test-unit
  - gem install --no-rdoc --no-ri rake-compiler
script: rake test
