language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - ruby-head
branches:
  only:
    - master
install: true
before_script:
  - gem install --no-rdoc --no-ri rake
  - gem install --no-rdoc --no-ri rdoc
  - gem install --no-rdoc --no-ri test-unit
  - gem install --no-rdoc --no-ri rake-compiler
script: rake test
