language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
  - ruby-head
branches:
  only:
    - master
before_script:
  - gem install --no-rdoc --no-ri --version '~> 3.12' rdoc
  - gem install --no-rdoc --no-ri --version '~> 2.5.2' test-unit
  - gem install --no-rdoc --no-ri --version '~> 0.7.1' rake-compiler
script: rake test
