sudo: false

language: ruby

cache:
  - bundler

bundler_args: --jobs 1 --retry 5 --without development --path vendor/bundle

rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - ruby-head

env:
  - COMPILER=gcc
  - COMPILER=clang

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - export GEM_ARGUMENTS=$(ruby -e 'puts Gem::Version.new(RUBY_VERSION) > Gem::Version.new("2.6.0") ? "--no-rdoc --no-ri" : "--no-document"')
  - gem install "$GEM_ARGUMENTS" bundler
  - export CC=$(which $COMPILER)

before_script:
  - bundle exec rake clean
  - bundle exec rake clobber

script:
  - bundle exec rake test

after_success:
  - bundle exec rake benchmark
