language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ree
  - ruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: 1.8.7
    - rvm: ruby-head
    - rvm: rbx-18mode
    - rvm: rbx-19mode
branches:
  only:
    - master
before_script:
  - travis_retry gem install --no-rdoc --no-ri rake rake-compiler test-unit rdoc
script: rake test
