language: ruby
cache: bundler
bundler_args: --jobs 4 --retry 2 --without development
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head
  - rbx-19mode
env:
  - COMPILER=gcc
  - COMPILER=clang
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-19mode
branches:
  only:
    - master
before_script:
  - export CC=$COMPILER
script: bundle exec rake test
