language: ruby
cache: bundler
bundler_args: --jobs 4 --retry 4 --without development --path vendor/bundle
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - ruby-head
  - rbx
env:
  - COMPILER=gcc
  - COMPILER=clang
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx
branches:
  only:
    - master
script:
  - export CC=$COMPILER
  - bundle exec rake test
