sudo: false

language: ruby

cache:
  - bundler

bundler_args: --jobs 1 --retry 5 --without development --path vendor/bundle

rvm:
  - '2.3'
  - '2.4'
  - '2.5'
  - '2.6'

env:
  - COMPILER=gcc
  - COMPILER=clang

matrix:
  fast_finish: true

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

before_install:
  - gem install bundler
  - export CC=$(which $COMPILER)

before_script:
  - bundle exec rake clean
  - bundle exec rake clobber

script:
  - bundle exec rake test

after_success:
  - bundle exec rake benchmark
