sudo: false

language: ruby

cache:
  - bundler

bundler_args: --jobs 1 --retry 5 --without development --path vendor/bundle

rvm:
  - 2.1.10
  - 2.2.9
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - ruby-head
  - rbx

env:
  - COMPILER=gcc
  - COMPILER=clang

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - gem install --no-rdoc --no-ri bundler
  - export CC=$(which $COMPILER)

before_script:
  - bundle exec rake clean
  - bundle exec rake clobber

script:
  - bundle exec rake test

after_success:
  - bundle exec rake benchmark
