sudo: false

language: ruby

cache:
  - bundler

bundler_args: --jobs 1 --retry 5 --without development --path vendor/bundle

rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - ruby-head
  - rbx-2

env:
  - COMPILER=gcc
  - COMPILER=clang

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  - export CC=$(which $COMPILER)

before_script:
  - bundle exec rake clean clobber

script:
  - bundle exec rake test
